name: Dependency Updates

on:
  schedule:
    - cron: '0 0 1,5,10,15,20,25 * *' # Runs on the 1st, 5st, 10th ... of each month

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Switch to update-deps branch
        run: |
          git fetch origin
          if git ls-remote --exit-code --heads origin update-deps; then
            git switch update-deps
            git reset --hard origin/master
          else
            git switch master
            git branch -D update-deps || true
            git switch -c update-deps
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update dependencies
        id: update_deps
        run: |
          pnpm update --latest --save-exact
          if git diff --quiet; then
            echo "No updates found"
            echo "UPDATE_FOUND=false" >> $GITHUB_ENV
          else
            echo "Updates found"
            echo "UPDATE_FOUND=true" >> $GITHUB_ENV
          fi

      - name: Check linter
        if: env.UPDATE_FOUND == 'true'
        run: pnpm run check

      - name: Check typing
        if: env.UPDATE_FOUND == 'true'
        run: pnpm run check-typing

      - name: Run tests with coverage
        if: env.UPDATE_FOUND == 'true'
        run: pnpm run coverage
        env:
          CI: true

      - name: Commit dependency updates if found
        if: env.UPDATE_FOUND == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(deps): update latest dependencies"
          git push origin update-deps
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}

      - name: Create Pull Request
        if: env.UPDATE_FOUND == 'true'
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          branch: update-deps
          base: master
          title: 'chore(deps): update latest dependencies'
          body: 'Automated dependency update via pnpm update --latest'
          labels: dependencies
          commit-message: 'chore(deps): update latest dependencies'
