name: Release

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: "Valid semver (x.x.x) or strategy (patch, minor, major)"
        default: "patch"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version
        run: yarn version ${{ github.event.inputs.strategy }}

      - name: Update changelog
        id: changelog
        run: |
          yarn install
          CHANGELOG=$(yarn conventional-changelog -p conventionalcommits -r -u 0)
          echo -e "${CHANGELOG}\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
          echo "::set-output name=body::$(echo "${CHANGELOG}" | tail -n +3 | sed ':a;N;$!ba;s/\n/%0A/g;s/\r/%0D/g')"

      - name: Log changes
        run: |
          echo "The changelog will be : ${{ steps.changelog.outputs.body }}"

      - name: Get version
        id: package-version
        run: echo "::set-output name=current-version::$(node -p "require('./package.json').version")"

      - name: Commit and tag release
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "chore(release): v${{ steps.package-version.outputs.current-version }}"
          git tag v${{ steps.package-version.outputs.current-version }}
          git push --follow-tags

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.body }}
          tag_name: v${{ steps.package-version.outputs.current-version }}
          name: v${{ steps.package-version.outputs.current-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
